#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_shock_part5_header shock_part5.mod LOGS_part5

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
